name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the Meson build type here (release, debug)
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository including submodules
      - uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are initialized

      # Install Meson, Eigen3, pkg-config, and other dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build openmpi-bin libopenmpi-dev libeigen3-dev pkg-config

      # Debug step to verify Eigen3 installation
      - name: Verify Eigen3 Installation
        run: |
          pkg-config --modversion eigen3
          pkg-config --cflags eigen3
          pkg-config --libs eigen3

      # Configure Meson, ensuring that the build is set up correctly
      - name: Configure Meson
        run: |
          PKG_CONFIG_PATH=/usr/include/eigen3 meson setup ${{github.workspace}}/builddir --buildtype=${{env.BUILD_TYPE}}

      # Compile the project
      - name: Build
        working-directory: ${{github.workspace}}/builddir
        run: meson compile

      # Run tests (if applicable)
      - name: Test
        working-directory: ${{github.workspace}}/builddir
        run: meson test